# Generated by Django 5.2.1 on 2025-05-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, help_text='Profily, které tento uživatel sleduje', related_name='followed_by', to='core.profile'),
        ),
    ]
