# Generated by Django 5.2.1 on 2025-05-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_followers_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, help_text='Kdo tento profil sleduje (větve reverse vztahu).', related_name='followers', to='core.profile'),
        ),
    ]
